### ISSUE TITLE
Container process keeps hanging and disconnecting CIFS share

### ISSUE THREAD

**Issue by g4m3r7ag** [binhex/arch-rtorrentvpn#178]
I recently setup the rtorrentvpn container with AirVPN. The container runs initially without issue, connects to the VPN and appears to be working great. But then frequently hangs, the rutorrent UI times out and then after a couple of minutes it reconnects. It's also causing my mounted CIFS share to hang, and then reconnect. The CIFS share issue started directly after setting up this container. I've currently stopped the container just to verify the CIFS issue also stops. Below is a screenshot of the Ubuntu 18.04 console a few minutes after rebooting. If I leave the container running the console just keeps repeating this at random intervals it seems. I've also included my compose config for the container. Any ideas? 

![Screenshot from 2021-04-03 04-54-06](https://user-images.githubusercontent.com/46694420/113473731-5a105a80-9439-11eb-97a2-26d1f1f0b601.png)

```
    rtorrent:
      image: binhex/arch-rtorrentvpn
      container_name: rtorrent
      cap_add:
        - NET_ADMIN
      environment:
        - PUID=1000
        - PGID=1000
        - VPN_ENABLED=yes
        - VPN_PROV=airvpn
        - VPN_CLIENT=openvpn
        - ENABLE_PRIVOXY=yes
        - ENABLE_RPC2=yes
        - ENABLE_RPC2_AUTH=yes
        - ENABLE_WEBUI_AUTH=yes
        - RPC2_USER=user
        - RPC2_PASS=pass
        - WEBUI_USER=user
        - WEBUI_PASS=pass
        - LAN_NETWORK=192.168.1.0/24,192.168.40.0/24
        - NAME_SERVERS=10.4.0.1 (this is the AirVPN DNS server) 
        - PHP_TZ=America/New_York
        - UMASK=022
      ports:
        - 38110:9080
        - 8118:8118
      restart: unless-stopped
      volumes:
        - /docker-data/dl-stack/rtorrent:/config
        - /mnt:/mnt
        - /etc/localtime:/etc/localtime:ro
```
